name: lol-esports-pick-bot CI/CD
on:
  push:
    branches:
      - main  # Change this if needed
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Install Maven Dependencies
        run: mvn clean package
      - name: Inspect JAR contents
        run: jar tf target/***-1.0-SNAPSHOT-all.jar
      - name: List target files
        run: ls -al target/
      - name: Rename JAR
        run: mv target/***-1.0-SNAPSHOT-all.jar target/function.jar
      - name: Zip Lambda Package
        run: zip function.zip target/function.jar
      - name: Unzip Lambda Package
        run: unzip -l function.zip
      - name: Deploy Lambda
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{ secrets.LAMBDA_FUNCTION_NAME }}
          zip_file: function.zip
          handler: net.lbku.handler.NotificationHandler::handleRequest
