name: lol-esports-pick-bot CI/CD
on:
  push:
    branches:
      - main  # Change this if needed
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Install Maven Dependencies
        run: mvn clean package
      - name: Prepare Lambda Package
        run: |
          mkdir -p build
          cp target/*-shaded.jar build/
          cd build
          unzip *-shaded.jar
          zip -r ../function.zip *
      - name: Deploy Lambda
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{ secrets.LAMBDA_FUNCTION_NAME }}
          zip_file: function.zip
